In [1]:
import numpy as np
import copy
import math
import random

from Tester import Tester

In [2]:
tester = Tester()

In [3]:
loop_tiling_lst =   [ 
                        [{"weight": 2}, {"filter": 2}, {"channel": 2}, {"output": 2}],
                        [{"filter": 4}, {"output": 4}, {"channel": 4}, {"weight": 4}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
parallel_for_dims = ["channel", "output"]
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[8 9 1 7 6 6 7 4 8 1 1 4 7 6 4]
 [1 4 6 5 6 1 2 5 9 0 0 6 0 3 4]
 [8 8 4 1 3 4 5 1 4 6 9 4 8 1 0]
 [7 3 1 3 9 6 9 0 6 8 6 7 4 5 2]
 [1 8 5 8 5 5 9 8 7 5 4 7 4 2 7]
 [4 1 7 0 5 5 8 9 9 1 3 7 8 4 4]
 [5 3 6 7 0 0 8 0 4 3 7 6 0 6 8]
 [5 4 7 5 1 7 3 4 2 7 9 6 7 2 5]]

INPUT MEMORY SIZES:
[120, 28]
****************************************************************************************************

WEIGHT DATA:
[[[8 3 2 7 4 7 9 1]
  [7 9 4 8 2 1 3 8]
  [1 6 1 8 2 6 3 9]
  [1 9 7 0 4 7 6 0]
  [8 6 3 3 0 9 4 2]
  [2 7 6 7 9 0 2 5]
  [1 4 7 4 8 1 1 0]
  [2 4 7 2 8 7 3 2]]

 [[4 2 5 7 6 7 5 2]
  [4 5 1 0 2 9 0 7]
  [7 8 1 5 0 4 5 0]
  [2 6 0 3 7 8 4 0]
  [7 7 2 5 2 4 6 9]
  [3 3 0 0 9 0 7 3]
  [2 1 6 5 1 7 1 0]
  [3 1 6 1 8 0 6 6]]

 [[4 7 4 3 0 7 0 4]
  [1 0 0 0 6 0 4 9]
  [0 4 7 9 2 8 9 2]
  [3 

In [4]:
loop_tiling_lst =   [ 
                        [{"filter": 2}, {"channel": 2}, {"weight": 2}, {"output": 2}],
                        [{"filter": 4}, {"channel": 4}, {"weight": 4}, {"output": 4}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
parallel_for_dims = ["channel", "weight", "output"]
prefetch_factor = 0.5

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[5 3 7 8 5 0 3 6 4 1 2 6 0 0 5]
 [7 9 6 8 6 8 9 7 6 9 4 6 3 1 3]
 [6 7 6 3 6 0 2 2 1 7 5 1 9 0 3]
 [2 6 1 6 1 4 9 7 2 4 6 0 2 3 2]
 [9 8 5 1 9 6 5 8 1 7 6 5 9 6 9]
 [2 0 2 8 9 9 4 1 9 5 0 4 6 1 1]
 [6 6 6 4 9 5 2 3 5 0 1 6 6 5 4]
 [8 0 3 0 3 4 2 2 6 8 0 1 9 1 9]]

INPUT MEMORY SIZES:
[120, 28]
****************************************************************************************************

WEIGHT DATA:
[[[7 0 3 7 9 5 8 0]
  [8 5 7 1 0 3 4 9]
  [3 7 8 6 9 2 0 6]
  [0 2 9 2 0 9 8 6]
  [3 1 3 0 6 2 3 9]
  [2 4 2 6 8 4 1 9]
  [9 6 8 3 7 2 6 2]
  [7 6 7 1 4 4 5 9]]

 [[9 3 9 1 3 8 6 7]
  [6 4 5 7 4 4 5 4]
  [4 7 5 1 2 1 0 2]
  [0 2 0 8 0 0 0 3]
  [8 3 9 5 0 4 7 1]
  [6 6 9 4 9 9 7 9]
  [9 0 2 9 3 1 4 4]
  [2 1 6 0 5 3 3 6]]

 [[0 3 3 0 2 7 5 9]
  [3 8 1 6 7 1 9 1]
  [8 7 8 1 4 3 9 5]
  [5 

In [5]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 3}, {"weight": 3},  {"output": 2}], 
                        [{"channel": 3}, {"weight": 2},  {"output": 3},  {"filter": 3}],
                        [{"filter": 2},  {"weight": 3},  {"channel": 2}, {"output": 3}],
                        [{"channel": 2}, {"filter": 2},  {"output": 3},  {"weight": 3}],
                    ]

parallel_for_dims = ["channel", "output"]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3, 1]
expansion_factor = 0
                                                                                                                                                
tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, debug=False)
tester.test(full=False)

Total Input Channels:  36
Num Inputs per Channel:  107
Total Weight Filters:  24
Num Channels per Filter:  36
Num Weights per Filter:  54
Total Output Channels:  24
Num Outputs per Channel:  54

INPUT DATA:
[[8 6 0 ... 3 6 0]
 [6 5 9 ... 0 0 3]
 [2 9 7 ... 8 8 0]
 ...
 [9 9 2 ... 9 9 9]
 [3 4 6 ... 5 3 2]
 [3 9 9 ... 6 8 9]]

INPUT MEMORY SIZES:
[3852, 528, 68, 10]
****************************************************************************************************

WEIGHT DATA:
[[[0 7 6 ... 7 2 3]
  [8 9 7 ... 8 7 2]
  [5 3 9 ... 6 6 5]
  ...
  [3 2 3 ... 0 4 1]
  [7 3 4 ... 5 0 6]
  [9 9 6 ... 7 5 3]]

 [[3 6 9 ... 4 4 4]
  [4 5 6 ... 0 6 1]
  [2 4 0 ... 4 1 7]
  ...
  [0 6 3 ... 3 4 0]
  [6 7 6 ... 2 4 5]
  [2 3 3 ... 9 5 8]]

 [[3 7 0 ... 1 4 0]
  [1 9 9 ... 5 2 1]
  [1 8 6 ... 6 9 5]
  ...
  [7 5 1 ... 8 0 6]
  [9 4 3 ... 2 8 6]
  [3 6 4 ... 8 4 6]]

 ...

 [[0 8 0 ... 0 2 8]
  [5 2 7 ... 9 1 9]
  [2 1 0 ... 6 5 9]
  ...
  [2 4 9 ... 8 4 1]
  [5 3 5 ... 1 6 4]
  [0 3 1 ... 8 2 1]]


KeyboardInterrupt: 

In [ ]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}], 
                        [{"channel": 4}, {"weight": 4},  {"output": 4},  {"filter": 4}],
                        [{"filter": 4},  {"weight": 4},  {"channel": 4}, {"output": 4}],
                        [{"channel": 4}, {"filter": 4},  {"output": 4},  {"weight": 4}],
                    ]

parallel_for_dims = ["channel", "output"]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3, 1]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)