In [1]:
import numpy as np
import copy
import math
import random

from Tester import Tester

In [2]:
tester = Tester()

In [3]:
# loop_tiling_lst =   [ 
#                         [{"channel": 4}, {"filter": 2}, {"weight": 2}, {"output": 2}],
#                         [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
#                     ]

# # which data should write backs be enabled for
# write_backs = {"input", "weight", "output"}
# costs = [10, 5]
# expansion_factor = 0
# parallel_for_dims = ["output", "weight"]
# # parallel_for_dims = None
# prefetch_factor = 1

# tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
#              prefetch_factor=prefetch_factor, debug=False)
# tester.test(full=False)

In [4]:
loop_tiling_lst =   [ 
                        [{"channel": 4}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"output": 2}, {"filter": 2}, {"weight": 2}, {"channel": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
# parallel_for_dims = ["output", "weight"]
parallel_for_dims = None
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  8
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[5 7 0 4 9 2 5]
 [9 6 9 4 5 5 9]
 [7 2 9 0 3 7 2]
 [6 5 1 0 3 0 9]
 [9 0 5 4 1 8 5]
 [4 6 1 7 4 6 6]
 [3 8 0 9 0 7 9]
 [9 5 1 9 0 1 9]]

INPUT MEMORY SIZES:
[56, 6]
****************************************************************************************************

WEIGHT DATA:
[[[4 7 9 0]
  [3 2 8 7]
  [6 2 4 3]
  [2 1 5 6]]

 [[1 4 2 7]
  [8 5 8 0]
  [8 2 0 9]
  [1 8 9 8]]

 [[1 0 1 7]
  [0 1 2 1]
  [2 1 2 0]
  [4 1 1 7]]

 [[9 0 0 7]
  [8 2 7 5]
  [3 9 4 2]
  [7 4 0 4]]

 [[2 5 1 9]
  [8 0 9 6]
  [5 1 3 4]
  [7 8 6 4]]

 [[1 1 9 7]
  [0 0 8 8]
  [7 3 7 2]
  [8 5 9 5]]

 [[8 4 1 9]
  [6 9 6 5]
  [2 8 5 9]
  [8 5 3 1]]

 [[1 0 6 6]
  [8 8 8 4]
  [3 4 9 6]
  [4 7 1 0]]]

WEIGHT MEMORY SIZES:
[128, 8]
*****************************************************************************************

In [5]:
loop_tiling_lst =   [ 
                        [{"channel": 4}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
# parallel_for_dims = ["output", "weight"]
parallel_for_dims = None
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  8
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[5 3 9 3 2 3 5]
 [4 7 6 7 4 7 3]
 [6 5 5 5 2 3 6]
 [1 7 6 1 6 3 7]
 [6 1 3 4 9 3 0]
 [7 1 7 8 2 9 0]
 [6 2 9 5 8 1 5]
 [7 4 5 0 3 5 0]]

INPUT MEMORY SIZES:
[56, 6]
****************************************************************************************************

WEIGHT DATA:
[[[4 3 0 4]
  [5 6 1 0]
  [0 8 4 1]
  [4 5 7 1]]

 [[6 2 5 2]
  [3 0 7 0]
  [9 8 0 6]
  [6 0 6 3]]

 [[3 7 4 9]
  [5 3 6 6]
  [3 4 3 6]
  [9 7 0 8]]

 [[6 0 1 9]
  [4 6 0 1]
  [8 4 7 8]
  [7 0 1 1]]

 [[5 4 2 1]
  [2 4 6 9]
  [7 2 0 9]
  [0 7 8 9]]

 [[9 5 0 4]
  [1 1 8 9]
  [1 7 0 3]
  [5 0 2 5]]

 [[8 5 1 3]
  [9 8 3 8]
  [4 7 4 1]
  [2 0 0 8]]

 [[9 7 5 4]
  [8 9 4 9]
  [5 9 3 5]
  [0 5 6 2]]]

WEIGHT MEMORY SIZES:
[128, 8]
*****************************************************************************************

In [6]:
# loop_tiling_lst =   [ 
#                         [{"weight": 2}, {"filter": 2}, {"channel": 2}, {"output": 2}],
#                         [{"filter": 4}, {"output": 4}, {"channel": 4}, {"weight": 4}]
#                     ]

# # which data should write backs be enabled for
# write_backs = {"input", "weight", "output"}
# costs = [10, 5]
# expansion_factor = 0
# parallel_for_dims = ["filter", "channel", "output"]
# prefetch_factor = 1

# tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
#              prefetch_factor=prefetch_factor, debug=False)
# tester.test(full=False)

In [7]:
# loop_tiling_lst =   [
#                         [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
#                         [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
#                         [{"channel": 2}, {"filter": 2},  {"output": 2},  {"weight": 2}],
#                     ]

# # parallel_for_dims = ["channel", "output"]
# parallel_for_dims = None

# # which data should write backs be enabled for
# write_backs = {"input", "weight", "output"}
# costs = [10, 7, 3]
# expansion_factor = 0
# prefetch_factor = 1

# tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
#              prefetch_factor=prefetch_factor, debug=True)
# tester.test(full=False)

In [8]:
# loop_tiling_lst =   [
#                         [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
#                         [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
#                         [{"weight": 2}, {"filter": 2},  {"output": 2},  {"channel": 2}],
#                         [{"filter": 2}, {"output": 2},  {"channel": 2},  {"weight": 2}]
#                     ]

# # parallel_for_dims = ["channel", "output"]
# parallel_for_dims = None

# # which data should write backs be enabled for
# write_backs = {"output"}
# costs = [10, 7, 3, 1]
# expansion_factor = 0
# prefetch_factor = 1

# tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
#              prefetch_factor=prefetch_factor, debug=True)
# tester.test(full=False)

In [9]:
# loop_tiling_lst =   [
#                         [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
#                         [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
#                         [{"weight": 2}, {"filter": 2},  {"output": 2},  {"channel": 2}],
#                         [{"filter": 2}, {"output": 2},  {"channel": 2},  {"weight": 2}]
#                     ]

# # parallel_for_dims = ["channel", "output"]
# parallel_for_dims = None

# # which data should write backs be enabled for
# write_backs = {"input", "output"}
# costs = [10, 7, 3, 1]
# expansion_factor = 0
# prefetch_factor = 1

# tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
#              prefetch_factor=prefetch_factor, debug=True)
# tester.test(full=False)

In [10]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2},  {"output": 3}, {"weight": 2}],
                        [{"output": 3}, {"weight": 3},  {"filter": 3},  {"channel": 2}],
                        [{"output": 2}, {"filter": 3},  {"channel": 2},  {"weight": 3}]
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"output"}
costs = [10, 7, 3]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  35
Total Weight Filters:  27
Num Channels per Filter:  8
Num Weights per Filter:  18
Total Output Channels:  27
Num Outputs per Channel:  18

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52
   53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
   88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122
  123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174]
 [175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 1

In [11]:
# loop_tiling_lst =   [
#                         [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}],
#                         [{"filter": 2},  {"weight": 4},  {"channel": 3}, {"output": 4}],
#                         [{"channel": 3}, {"filter": 4},  {"output": 2},  {"weight": 4}],
#                     ]

# parallel_for_dims = ["channel", "output"]
# # parallel_for_dims = None

# # which data should write backs be enabled for
# write_backs = {"input", "weight", "output"}
# costs = [10, 7, 3]
# expansion_factor = 0
# prefetch_factor = 1

# tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
#              prefetch_factor=prefetch_factor, debug=False)
# tester.test(full=False)