In [1]:
import numpy as np
import copy
import math
import random

from Tester import Tester

In [2]:
tester = Tester()

In [3]:
loop_tiling_lst =   [ 
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
parallel_for_dims = ["output", "weight"]
# parallel_for_dims = None
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  4
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  4
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[1 0 4 6 6 0 4]
 [1 0 8 5 6 0 1]
 [0 6 3 3 7 2 2]
 [0 3 4 1 0 2 4]]

INPUT MEMORY SIZES:
[28, 6]
****************************************************************************************************

WEIGHT DATA:
[[[1 4 2 6]
  [6 1 2 2]
  [4 1 3 7]
  [9 5 3 0]]

 [[0 0 7 9]
  [1 6 1 4]
  [0 6 8 1]
  [4 4 9 5]]

 [[2 8 0 7]
  [1 6 3 0]
  [6 3 6 4]
  [5 4 7 2]]

 [[5 3 0 1]
  [4 0 6 2]
  [8 1 7 0]
  [7 5 8 4]]]

WEIGHT MEMORY SIZES:
[64, 8]
****************************************************************************************************

OUTPUT DATA:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT MEMORY SIZES:
[16, 4]
****************************************************************************************************

LOOP HIERARCHY
channel: 2
  filter: 2
    weight: 

In [4]:
loop_tiling_lst =   [ 
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
# parallel_for_dims = ["output", "weight"]
parallel_for_dims = None
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  4
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  4
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[5 6 8 2 4 5 3]
 [0 6 0 5 1 6 1]
 [9 3 2 4 2 2 3]
 [6 9 8 5 7 2 9]]

INPUT MEMORY SIZES:
[28, 6]
****************************************************************************************************

WEIGHT DATA:
[[[8 0 2 9]
  [6 8 1 7]
  [3 9 8 5]
  [0 4 3 1]]

 [[9 9 9 2]
  [0 8 1 4]
  [4 8 6 3]
  [5 7 8 0]]

 [[6 4 0 8]
  [3 6 7 7]
  [8 8 2 4]
  [7 6 2 7]]

 [[3 4 0 7]
  [2 4 0 3]
  [8 9 1 0]
  [3 8 1 3]]]

WEIGHT MEMORY SIZES:
[64, 8]
****************************************************************************************************

OUTPUT DATA:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT MEMORY SIZES:
[16, 4]
****************************************************************************************************

LOOP HIERARCHY
channel: 2
  filter: 2
    weight: 