In [1]:
import numpy as np
import copy
import math
import random
import sys
sys.path.append('../code/')

from Tester import Tester

In [2]:
tester = Tester()

In [3]:
loop_tiling_lst =   [ 
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
# parallel_for_dims = ["weight", "output"]
parallel_for_dims = None
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  4
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  4
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]

INPUT MEMORY SIZES:
[28, 6]
****************************************************************************************************

WEIGHT DATA:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]

WEIGHT MEMORY SIZES:
[64, 8]
****************************************************************************************************

OUTPUT DATA:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT MEMORY SIZES:
[16, 4]
************************************************************

In [4]:
loop_tiling_lst =   [ 
                        [{"weight": 2}, {"filter": 2}, {"channel": 2}, {"output": 2}],
                        [{"filter": 4}, {"output": 4}, {"channel": 4}, {"weight": 4}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
# parallel_for_dims = ["filter", "channel", "output"]
parallel_for_dims = None
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[6 3 0 5 7 5 3 6 1 7 6 6 1 3 8]
 [5 3 1 1 1 5 7 3 9 0 0 2 7 2 3]
 [9 6 8 7 4 6 8 9 4 1 1 5 6 1 7]
 [2 4 3 5 6 1 1 4 8 4 2 0 8 9 1]
 [7 8 1 0 1 1 0 1 7 0 7 7 6 3 1]
 [0 9 2 0 8 2 5 2 1 7 2 5 2 6 2]
 [1 8 6 6 8 5 4 7 5 6 3 3 5 6 3]
 [5 3 6 2 5 7 9 5 5 3 5 5 8 2 9]]

INPUT MEMORY SIZES:
[120, 28]
****************************************************************************************************

WEIGHT DATA:
[[[7 1 4 4 6 6 1 6]
  [4 7 4 0 5 2 6 8]
  [8 6 1 3 9 7 1 8]
  [5 7 8 0 3 7 2 3]
  [5 3 7 3 9 6 6 4]
  [3 1 7 0 9 8 4 6]
  [5 0 8 4 8 3 8 4]
  [6 2 8 7 2 0 8 0]]

 [[9 6 7 2 1 2 8 7]
  [5 4 9 2 6 9 7 8]
  [9 7 8 7 1 4 9 3]
  [0 8 8 6 6 1 0 6]
  [4 6 3 9 6 0 7 4]
  [2 4 9 1 7 7 6 9]
  [5 1 4 0 8 2 2 3]
  [7 2 6 9 3 5 4 3]]

 [[7 9 7 2 5 4 0 5]
  [0 4 1 4 9 0 0 3]
  [0 4 6 6 0 0 7 4]
  [4 

In [5]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
                        [{"channel": 2}, {"filter": 2},  {"output": 2},  {"weight": 2}],
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]]

INPUT MEMORY SIZES:
[120, 28, 6]
****************************************************************************************************

WEIGHT DATA:
[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  

In [6]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
                        [{"weight": 2}, {"filter": 2},  {"output": 2},  {"channel": 2}],
                        [{"filter": 2}, {"output": 2},  {"channel": 2},  {"weight": 2}]
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"output"}
costs = [10, 7, 3, 1]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  16
Num Inputs per Channel:  31
Total Weight Filters:  16
Num Channels per Filter:  16
Num Weights per Filter:  16
Total Output Channels:  16
Num Outputs per Channel:  16

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48
   49  50  51  52  53  54  55  56  57  58  59  60  61]
 [ 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
   80  81  82  83  84  85  86  87  88  89  90  91  92]
 [ 93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
  111 112 113 114 115 116 117 118 119 120 121 122 123]
 [124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141
  142 143 144 145 146 147 148 149 150 151 152 153 154]
 [155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
  173 174 175 176 177 178 179 180 181 182 183 184 185]
 [186 187 188 189 19

In [7]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"output": 3},  {"weight": 3}],
                        [{"filter": 2},  {"channel": 3},  {"weight": 2}, {"output": 3}]
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "output"}
costs = [10, 7]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  6
Num Inputs per Channel:  14
Total Weight Filters:  4
Num Channels per Filter:  6
Num Weights per Filter:  6
Total Output Channels:  4
Num Outputs per Channel:  9

INPUT DATA:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79 80 81 82 83]]

INPUT MEMORY SIZES:
[84, 12]
****************************************************************************************************

WEIGHT DATA:
[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]]

 [[ 24  25  26  27  28  29]
  [ 30  31  32  33  34  35]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]]

 [[ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]
  [ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]]

 [[ 72  73  74  75  76  77]
  [ 78  79  80

In [14]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 3}, {"output": 2},  {"weight": 3}],
                        [{"filter": 2},  {"channel": 3},  {"weight": 2}, {"output": 2}],
                        [{"filter": 2},  {"channel": 3},  {"output": 3}, {"weight": 2}]
    
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "output"}
costs = [10, 7, 3]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  27
Num Inputs per Channel:  23
Total Weight Filters:  8
Num Channels per Filter:  27
Num Weights per Filter:  12
Total Output Channels:  8
Num Outputs per Channel:  12

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22]
 [ 23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
   41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
   64  65  66  67  68]
 [ 69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
   87  88  89  90  91]
 [ 92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
  110 111 112 113 114]
 [115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132
  133 134 135 136 137]
 [138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
  156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
  179 180 181 182 183]
 [184 185 186 187 18

In [8]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}],
                        [{"filter": 2},  {"weight": 4},  {"channel": 3}, {"output": 4}],
                        [{"channel": 3}, {"filter": 4},  {"output": 2},  {"weight": 4}],
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  18
Num Inputs per Channel:  63
Total Weight Filters:  24
Num Channels per Filter:  18
Num Weights per Filter:  48
Total Output Channels:  24
Num Outputs per Channel:  16

INPUT DATA:
[[6 3 8 ... 1 5 0]
 [8 4 3 ... 4 8 8]
 [7 1 4 ... 2 2 1]
 ...
 [0 0 9 ... 8 2 4]
 [6 3 8 ... 6 1 6]
 [7 5 0 ... 9 7 8]]

INPUT MEMORY SIZES:
[1134, 207, 15]
****************************************************************************************************

WEIGHT DATA:
[[[5 5 7 ... 8 6 4]
  [9 8 4 ... 0 8 3]
  [6 0 1 ... 0 3 4]
  ...
  [2 5 5 ... 9 4 8]
  [7 4 5 ... 3 6 6]
  [3 3 8 ... 5 6 0]]

 [[6 9 6 ... 2 1 7]
  [2 5 3 ... 3 1 3]
  [1 7 8 ... 9 7 3]
  ...
  [7 7 7 ... 6 5 7]
  [1 1 1 ... 1 9 2]
  [2 3 9 ... 1 1 6]]

 [[4 8 3 ... 6 3 5]
  [2 8 2 ... 4 4 4]
  [1 7 6 ... 3 3 2]
  ...
  [5 8 8 ... 0 4 8]
  [3 2 7 ... 1 5 3]
  [5 5 7 ... 6 3 7]]

 ...

 [[4 6 3 ... 3 8 5]
  [6 7 8 ... 8 9 3]
  [7 2 5 ... 8 0 5]
  ...
  [1 8 5 ... 3 1 4]
  [4 0 4 ... 7 6 7]
  [5 0 5 ... 2 4 2]]

 [[5

In [9]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}],
                        [{"filter": 2},  {"weight": 4},  {"channel": 3}, {"output": 4}],
                        [{"channel": 3}, {"filter": 4},  {"output": 2},  {"weight": 4}],
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"weight", "output"}
costs = [10, 7, 3]
expansion_factor = .5
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  18
Num Inputs per Channel:  63
Total Weight Filters:  24
Num Channels per Filter:  18
Num Weights per Filter:  48
Total Output Channels:  24
Num Outputs per Channel:  16

INPUT DATA:
[[8 0 0 ... 8 2 0]
 [6 7 4 ... 5 7 0]
 [3 0 9 ... 2 0 0]
 ...
 [8 0 1 ... 8 4 4]
 [0 7 0 ... 7 9 8]
 [6 8 9 ... 0 8 1]]

INPUT MEMORY SIZES:
[1701, 310, 22]
****************************************************************************************************

WEIGHT DATA:
[[[9 5 6 ... 3 9 5]
  [9 2 5 ... 3 2 8]
  [4 4 1 ... 7 3 4]
  ...
  [2 0 4 ... 9 6 9]
  [6 0 5 ... 5 6 4]
  [4 5 1 ... 7 6 3]]

 [[5 3 2 ... 4 9 7]
  [5 3 8 ... 0 9 7]
  [6 5 5 ... 2 2 2]
  ...
  [4 8 0 ... 4 5 9]
  [7 8 0 ... 2 8 1]
  [1 8 4 ... 4 2 9]]

 [[6 9 5 ... 9 5 5]
  [0 3 0 ... 4 4 4]
  [3 2 5 ... 6 2 5]
  ...
  [0 2 3 ... 6 7 5]
  [0 8 9 ... 3 8 7]
  [2 8 6 ... 9 9 2]]

 ...

 [[0 1 6 ... 9 5 0]
  [2 4 9 ... 7 8 4]
  [4 1 3 ... 6 9 0]
  ...
  [3 7 7 ... 4 4 2]
  [9 5 1 ... 6 6 5]
  [0 8 8 ... 5 7 3]]

 [[4