In [1]:
import numpy as np
import copy
import math
import random
import sys
sys.path.append('../code/')

from Tester import Tester

In [2]:
tester = Tester()

In [3]:
loop_tiling_lst =   [ 
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
parallel_for_dims = ["weight", "output"]
# parallel_for_dims = None
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  4
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  4
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]

INPUT MEMORY SIZES:
[28, 6]
****************************************************************************************************

WEIGHT DATA:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]

WEIGHT MEMORY SIZES:
[64, 8]
****************************************************************************************************

OUTPUT DATA:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT MEMORY SIZES:
[16, 4]
************************************************************

In [4]:
loop_tiling_lst =   [ 
                        [{"weight": 2}, {"filter": 2}, {"channel": 2}, {"output": 2}],
                        [{"filter": 4}, {"output": 4}, {"channel": 4}, {"weight": 4}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
parallel_for_dims = ["filter", "channel", "output"]
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[2 9 8 0 2 2 0 2 2 1 5 5 8 1 9]
 [8 6 8 0 2 9 7 3 5 9 2 8 4 5 8]
 [4 1 9 3 9 3 3 9 5 2 6 1 4 4 6]
 [1 4 0 1 0 1 3 4 2 2 2 4 5 6 1]
 [5 9 2 4 4 6 2 0 5 2 9 2 9 3 5]
 [9 3 2 3 2 8 7 2 6 2 9 5 3 1 7]
 [5 6 5 5 7 2 5 4 1 3 9 9 8 5 8]
 [5 9 5 8 7 0 7 5 6 1 9 6 6 8 7]]

INPUT MEMORY SIZES:
[120, 28]
****************************************************************************************************

WEIGHT DATA:
[[[8 0 5 2 9 1 4 1]
  [7 8 7 2 9 0 7 4]
  [6 5 7 4 9 4 3 4]
  [4 4 5 7 2 0 9 4]
  [4 1 5 5 1 0 7 3]
  [2 7 1 9 7 6 3 8]
  [0 2 0 1 6 6 9 7]
  [8 0 2 5 0 5 8 9]]

 [[2 1 2 6 9 5 8 3]
  [1 6 2 4 5 4 5 8]
  [2 7 2 5 3 0 1 6]
  [3 8 3 1 4 5 0 2]
  [5 0 6 6 8 7 2 2]
  [8 2 6 5 8 2 3 2]
  [3 1 2 2 1 9 1 5]
  [7 7 1 2 4 7 4 6]]

 [[9 1 1 8 2 7 5 3]
  [6 0 5 7 5 8 2 1]
  [6 9 1 5 1 5 5 0]
  [6 

In [5]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"output": 2},  {"weight": 2}, {"channel": 2}],
                        [{"channel": 2}, {"filter": 2},  {"output": 2},  {"weight": 2}],
                    ]

parallel_for_dims = ["weight", "channel"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]]

INPUT MEMORY SIZES:
[120, 28, 6]
****************************************************************************************************

WEIGHT DATA:
[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  

start 17992
end 17992
start 10744
end 10744
start 12736
end 12736
start 6304
end 6304
start 18348
end 18348
start 8392start 2472
end 2472

end 8392
start 10756
end 10756
start 3304
end 3304start 16444
end 16444
start 10396

end 10396
start 11348
end 11348
start 17116
end 17116
start 1420
end 1420
start 18052
end 18052
start 3584
end 3584
start 14968
end 14968
start 17864
end 17864
start 16812
end 16812
start 4952
end 4952
start 17948
end 17948
start 11660
end 11660
start 14612
end 14612
start 12996
end 12996
start 4372
end 4372
start 16392
end 16392
start 13504
end 13504
start 17272
end 17272
start 10628
end 10628
start 3804
end 3804
start 17544
end 17544
start 14432
end 14432
start 14744
end 14744
start 17536
end 17536
start 12924
end 12924
start start 17504
end 17504
start 18196
end 18196
268
end 268
start 9408
end 9408
start 14376
end 14376
start 17952
end 17952
start 3772
end 3772
start 10964
end 10964
start 18192
end 18192
start 2828
end 2828
start 14528
end 14528
start 18272
end 

In [6]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
                        [{"weight": 2}, {"filter": 2},  {"output": 2},  {"channel": 2}],
                        [{"filter": 2}, {"output": 2},  {"channel": 2},  {"weight": 2}]
                    ]

parallel_for_dims = ["channel", "output"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"output"}
costs = [10, 7, 3, 1]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=True)
tester.test(full=False)

Total Input Channels:  16
Num Inputs per Channel:  31
Total Weight Filters:  16
Num Channels per Filter:  16
Num Weights per Filter:  16
Total Output Channels:  16
Num Outputs per Channel:  16

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48
   49  50  51  52  53  54  55  56  57  58  59  60  61]
 [ 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
   80  81  82  83  84  85  86  87  88  89  90  91  92]
 [ 93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
  111 112 113 114 115 116 117 118 119 120 121 122 123]
 [124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141
  142 143 144 145 146 147 148 149 150 151 152 153 154]
 [155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
  173 174 175 176 177 178 179 180 181 182 183 184 185]
 [186 187 188 189 19

start 18404
end 18404
start 17968
end 17968
start 2056
end 2056
start 6056
end 6056
start 12516
end 12516
start start 11560
end17288
endstart  2520
end 11560
 172882520

start 15104start 
10820
end start 17320
end10820end 
 15104
17320
start 11860
end 11860
start 11016
end 11016
start 15664
end 15664
start 7692
endstart 10208
end 10208
 7692
start start 2340
endstart 1794418344
end 17944 2340

end 18344
start 10900

end 10900
start 13656
end 13656
start 6052
end 6052
start 16896
end 16896
start 14112
end 14112
start 15024
end 15024
start 12000
end 12000
start 12964
end 12964
start 17416
end 17416
start 1360
end 1360
start 12160
start 12196
end 12196
end start 16512
end 16512
12160
start 17396
end 17396
start 11244
end 11244
start 608
end 608
start 15180
end 15180
start 13044
end 13044
start 5456
end 5456
start 2768
end 2768
start 17164
end 17164
start start 5028
end12700
end 5028
 12700
startstart 14916
end 2700
end  2700
14916
start 3000
end 3000
start start9600 15392
end 15392

start

7332
start 18016
endstart 16832 18016

start 1608
end 1608
end 16832
start 18036
end 18036
start 11652
end 11652
start 14208
end 14208
start 11624
end 11624
start 17660
end 17660
start 12328
end 12328
start 15608
end 15608
start 1540
end 1540
start 10000
end 10000
start 16960
end 16960
start 18224
end 18224
start 10680
end 10680
start 16548
end 16548
start start 10452
end 10452
start 18032
end 18032
5352
end 5352
start 8600
end 8600
startstart 7200
end 7200
 start 11072
end 11072
15060start 15220
end
 15220
end 15060
start 2404
end 2404
start 8116
end 8116
start 17032
end 17032
start 12400
end 12400
start 9048
end 9048
start 4128
end 4128
start 5536
end 5536
start 1820
end 1820
start 15804
end 15804
start 13112
endstart 9220
end 13112
 9220
start 7172
end 7172
start 16516
end start 11632
end 11632
16516
start 10036
end 10036
start 9236
end 9236
start 13668
end 13668start 9056start

end 9056 
4044
end 4044
start 7324
end 7324
start 3152
end 3152start
 6444
endstart 11248
end 11248
start

start 5004
end 5004
start 14676
end 14676
start 3604
end 3604
start 17584
end 17584
start 9732
end 9732
start 8444
end 8444
start 6264
end 6264
start 13448
end 13448
start 18020
end 18020
start 15248
end 15248
start 7912
end 7912
start start 7580
end 7580
17868
end 17868
start 8460
end 8460
start 17740
end 17740
start 6436
end 6436
start 15668
end 15668
start 11492
end 11492
start 8936
end 8936
start 9808
end 9808
start 3652
end 3652
start 10480
end 10480
start 13476
end 13476
start 9744
endstart 12336
end 12336
 start 11404
end 11404
9744
start 17644
end 17644
start 15632
end 15632
start 11396
endstart 15944
end 15944
 11396
start 2264
end 2264
start 17564
end 17564
start 6372
end 6372
start start 15560
end16492
 end 16492
15560
start 10796start 15408

end 15408
end 10796
start 17316
endstart 17624
end 17316
 17624
start 6636
end 6636
start 12152
end 12152
start 12932
end 12932
start 4936
end 4936
start 7204
end 7204
start 12408
start 8128end
 start 1400
end 1400
12408
end 8128
start 

start 10016
endstart  7712
end 7712
10016
start 6680
end 6680
start 4864
end 4864
start 17816
end 17816start 6660
end 6660

start 14020
end 14020
start 11868
end 11868
start 2088
end 2088
start 9016
end 9016
start 16448
end 16448
start 13296
end 13296
start 2372
end 2372
start 6368
end 6368
start 14412
end 14412
start 17268
end 17268
start 2304
end 2304
start 16468
end 16468
start 7456
end 7456
start 7876
end 7876
start 18072
end 18072
start 17976
end 17976
start 16364
end 16364
start 3388
end 3388
start 15396
end 15396
start 17788
end 17788
start 15404
end 15404
start 17708
end 17708
start 13156
end 13156
start 5744
end 5744
start 18400
end 18400
start 3212
end 3212
start 2564
end 2564start 8712

end 8712
startstart 2764
end 2764
 18116
start 11100
end start 18116
5356
end 5356
end 11100
start 8236
end 8236
start 13608
end 13608
start 6996
end 6996
start 12648
end 12648
start 18176
end 18176
start 16724
end 16724
start 5108
end 5108
start 7868
end 7868
start 13896
end 13896
start 4388

start 17824
end 17824
start 11060
end 11060
start 16544start 7008
end 7008

start 5472end
end  5472
16544
start 13304
end 13304
start 12136
end 12136
start 11160
start 17812
end 17812
end 11160
start 17680
end 17680
start 2696
end 2696
start 16344
end 16344
start 4000
end 4000
start 18392
end 18392
start 17240
end 17240
start 14852
end 14852
start 16756
end 16756
start 8044
end 8044
start 10548start 13852
end 13852

end 10548
start 12732
end 12732
start 9928
end 9928
start 8536
end 8536
start 15812
end 15812
start 17880
end 17880
start 11512
end 11512
start 10100
end 10100
start 5340
end 5340
start 2128
end 2128
start 3160
end 3160
start 16012
end 16012
start 7116
end 7116
start 17672
end 17672
start 6480
end 6480
start 13848
end 13848
start 12916
end 12916
start 2020
end 2020
start 6360
end 6360
start 11788
end 11788
start 8244
end 8244
start 13708
end 13708
start 17048
end 17048
start 17568start 14796
end 17568

end 14796
start 12948
end 12948
startstart start 7652
end 7652
start 122

start 13656
end 13656
start 6052
end 6052
start 16896
end 16896
start 14112
end 14112
start 15024
end 15024
start 12000
end 12000
start 9456
end 9456
start 8124
end 8124
start 2936
end 2936
start 10012
end 10012
start 14940
end 14940
start 3972
end 3972
start 7428
end 7428
start 18316
end 18316start 12964
end 12964

start 140
end 140
start 17416
end 17416
start 1360
end 1360
start 12196
end 12196
start 12160
end 12160
start 16512
end 16512
start 17396
end 17396
start 11244
end 11244
start 608
end 608
start 5012
end 5012
start 15180
end 15180
start 13044
end 13044
start 2768
end 2768
start 5456
end 5456
start 17164
end 17164
start 12700
end 12700
start 5028
end 5028
start 2700
end 2700
start 14916
end 14916
start 3000
end 3000
start 16380
end 16380
start 512
end 512
start 6356
end 6356
start 9844
end 9844
start 5256
end 5256
start 16668
end 16668
start 3364
end 3364
start 11292
end 11292
start 17480
end 17480
start 8956
end 8956
start 15392
end 15392
start 32
end 32
start 9600
end 9600


start 11552
end 11552
start 8972
end 8972
start 10124
end 10124
start 12404
end 12404
start 17532
end 17532
start 4088
end 4088
start 16948
end 16948
start 17640
end 17640
start 17244
end 17244
start 2456
end 2456
start 11400
end 11400
start 15116
end 15116
start 11168
end 11168
start 6328
end 6328
start 148
end 148
start 5380
end 5380
start 7940
end 7940
start 15600
end 15600
start 17936
end 17936
start 12672
end 12672
start 12744
end 12744
start 9876
end 9876
start 5312
end 5312
start 16584
end 16584
start 10876
end 10876
start 12448
end 12448
start 10088
end 10088
start 10460
end 10460
start 11052
end 11052
start 14616
end 14616
start 3116
end 3116
start 2584
endstart 6708 2584

end 6708
start 16528
end 16528
start 4724
end 4724
start 6440
end 6440start 
16888
end 16888
start 8876
end 8876
start 17424
end 17424
start 1380
end 1380
start 7660
end 7660
start 17080
end 17080
start 15332
end 15332
start 12960
end 12960
start 14908
end 14908
start 264
end 264
start 11880
end 11880
start 

start 17992
end 17992
start 12736
end 12736
start 6304
end 6304
start 8392
end 8392
start 18348
endstart  183482472
end 2472
start 10756
end 10756

start 16444
end 16444
start 10396
end 10396
start 3304
end 3304
start 11348
end 11348
start 17116
end 17116
start 1420
end 1420
start 18052
end 18052
startstart 14968
end 14968
 3584
end 3584
start 17864
end 17864
start 16812
end 16812
start 4952
end 4952
start 17948
end 17948
start 11660
end 11660
start 14612
end 14612
start 12996
end 12996
start 4372
end 4372
start 16392
end 16392
start 13504start 17272
end 17272

end 13504start 10628
end 10628

start 3804
end 3804start 
17544
end 17544
start 14432
end 14432
start 14744
end 14744
start 17536
end 17536
start 12924
end 12924
start 268
end 268
start 17504
end 17504
start 18196
end 18196
start 9408
end 9408
start 14376
end 14376
start 17952
end 17952
start 3772
end 3772
start 10964
end 10964
start 18192
end 18192
start 14528
end 14528
start 2828
end 2828
start 18272
end 18272
start 16952
end 

start 13540
end 13540
start 2704
endstart 5608
end 5608
start 1692
end 1692
 2704
start 8680
end 8680
start 12048
end 12048
start 580
endstart 14864
end 14864
 580start 12260
end 12260

start 14844
end 14844
start 11432
end 11432
start 3096
end 3096
start 18064
end 18064
start 12064
end 12064
start 9708
end 9708
start 12316
end 12316
start 15932
end 15932
start 3164
start 17856
end 17856
end 3164
start 6796
end 6796
start 9472
end 9472
start 2496
end 2496
start 16924
end 16924
start 3660
end 3660
start 5224
end 5224
start 14976
end 14976
start 14064
end 14064
start 1896
end 1896
start 10080
end 10080
start 16060
end 16060
start 17588
end 17588
start 11240
end 11240
start 12880
end 12880
start 13904
end 13904
start 15760
end 15760
start 10328
end 10328
start 9464
end 9464
start 7752
end 7752
start 440
end 440
start 3824
end 3824
start 12436
end 12436
start 7088
end 7088
start 16408
end 16408
start 16820
end 16820
start 15972
end 15972
start 3540
endstart 3004
end 3004
 3540
start 13072


start 9048
end 9048
start 4128
end 4128
start 5536
end 5536
start 1820
end 1820
start 15804
end 15804
start 13112
end 13112
start 7172
end 7172
start 9220
end 9220
start 11632
end 11632
start 16516
end 16516
start 10036
end 10036
start 17084
end 17084
start 5584
end 5584
start 9236
end 9236
start 7324
end 7324
start 4044
end 4044
start 13668
end 13668
start 9056
end 9056
start 6444
end 6444
start 3152
end 3152
start 11248
end 11248
start 13388
end 13388
start 3356
end 3356
start 8868
end 8868
start 3632
end 3632
start 5952
end 5952
start 5276
end 5276
start 12848
end 12848
start 8976
end 8976
start 10340
end 10340
start 5460
end 5460
start 15072
end 15072
start 15528
end 15528
start 10572
end 10572
start 11824
end 11824
start start 10912
end 10912
15660start 3736
end 3736

end 15660
start 1572
end 1572
start 7308
end 7308
start 17420
end 17420
start 1184
end 1184
start 14944
end 14944
start 8940
end 8940
start 548
end 548
start 13408
start 7388
end 7388end 
13408
start 2244
end 2244
st

start 8196
start 8960
end 8196start 17908
end 17908

end 8960
start 16640
end 16640
start 15992
end 15992
start 12240
end 12240
start 16332
end 16332
start 3148
end 3148
start 9004
end 9004
start 17508
end 17508
start 5940
end 5940
Passed Correctness Check

INPUT MEMORY HIERARCHY
****************************************************************************************************
Total Cost: 137696
####################################################################################################
Level:  4
Read Count: 992
Write Count: 0
Cost: 9920
####################################################################################################
Level:  3
Read Count: 7168
Write Count: 992
Cost: 57120
####################################################################################################
Level:  2
Read Count: 12288
Write Count: 7168
Cost: 58368
####################################################################################################
Level:  1
	Read Count: 0
	Wri

In [7]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}],
                        [{"channel": 2},  {"weight": 4},  {"filter": 3}, {"output": 4}],
                        [{"channel": 3}, {"filter": 4},  {"output": 2},  {"weight": 4}],
                    ]

parallel_for_dims = ["filter", "output"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0
prefetch_factor = 1

tester.setup(loop_tiling_lst, costs, expansion_factor, write_backs, parallel_for_dims=parallel_for_dims, 
             prefetch_factor=prefetch_factor, debug=False)
tester.test(full=False)

Total Input Channels:  12
Num Inputs per Channel:  63
Total Weight Filters:  36
Num Channels per Filter:  12
Num Weights per Filter:  48
Total Output Channels:  36
Num Outputs per Channel:  16

INPUT DATA:
[[6 5 2 9 4 8 6 5 9 0 5 5 7 7 2 5 3 0 7 2 4 3 2 5 1 7 4 5 4 5 6 0 5 3 8 1
  3 6 6 8 0 7 2 8 3 9 5 9 0 7 4 1 9 9 3 9 6 8 5 0 9 1 0]
 [4 6 0 8 6 1 0 8 4 3 8 1 2 0 6 1 3 8 4 5 0 4 7 2 4 1 9 7 4 5 1 9 2 0 5 8
  7 8 7 5 1 1 8 1 6 2 1 5 3 4 7 0 5 8 3 6 2 9 9 1 7 7 2]
 [1 2 1 0 9 4 0 5 7 1 6 2 0 1 1 7 6 7 6 8 9 8 0 0 2 3 6 6 1 3 2 6 9 6 5 6
  6 3 8 2 2 6 1 0 6 3 9 4 5 1 8 4 1 2 4 8 5 8 4 5 9 2 9]
 [8 9 7 4 4 1 0 6 1 7 5 6 1 0 6 9 3 5 1 7 6 7 0 5 5 7 2 7 0 1 1 6 6 3 3 5
  2 4 8 3 8 0 2 3 3 6 8 2 9 8 2 0 9 8 7 9 7 4 0 1 2 4 8]
 [7 4 3 7 5 2 0 0 1 3 1 7 9 0 6 4 3 1 5 9 7 1 3 3 5 9 0 5 6 8 8 5 8 5 4 6
  2 7 5 2 2 9 0 9 9 5 9 8 7 8 4 8 0 7 1 3 5 7 0 9 7 4 8]
 [0 1 2 2 6 1 5 3 0 6 9 8 5 8 0 8 2 0 9 2 6 7 0 9 1 0 7 9 9 7 0 2 2 8 0 9
  2 2 1 7 7 0 9 1 0 6 6 6 5 0 4 0 9 2 1 5 3 8 8 8 7 6 6]
 [7 3 7 

start 12540
start 11212
endend 12540
 11212
start 764
end 764
start 4608
end 4608
start 16144
start 16892end 16144

start 5988end 16892
end 5988
start 18220
start 11412
end 18220

end 11412
start 2280
endstart 3640
end 3640
start 6468
end 6468
 start 4940
2280end 4940
start 7068

end 7068
start 16636
end 16636
start 15012
end 15012
start 16196
end 16196
start 9044
end 9044
start 16412
end 16412
start 17988
end 17988
start 10924
end 10924
start 15264
end 15264
start 12588
end 12588
start 1812
end 1812
start 12920
end 12920
start 14300
end 14300
start 15000
end 15000
start 9028
end 9028
start 10884
end 10884
start 17632
end 17632
start 11920
end 11920
start 7292
end 7292
start 18356
end start 13900
end 13900
18356
start 7180
end 7180
startstart 14472
end 14472
 start 17228
end 17228
2712
end 2712
start 13600
end 13600
start 15916
end 15916
start 15388
end 15388
start 12608
end 12608
start 6120
end 6120
start 16208
end 16208
start 17040
end 17040
start 17960
end 17960
start 15352
end 1535

end 15904
start 18236
start 17940
start 11324
endend 17940
end start 3888
end 3888
 11324
18236
start 15868
end 15868
start 17348
end 17348
start 17492
end 17492
start 6668
end 6668
start 4504
end 4504
start 15004
end 15004
start 11932
end 11932
start 16588start 2400
end 2400

end 16588
start 16608
end 16608
start 17820
end 17820
start 17736
end 17736
start 12524
end 12524
startstart 12508 15520
end 15520

end 12508
start 7964
end 7964
start start 7992
12128start 2164
end end 7992
2164

start 9856
end 9856
end 12128
start 12208
start 10228
end 12208
end 10228
start 13328
end 13328
start 9428
end 9428
start 10472
end 10472
start 13824
end 13824
start 5992
end 5992
start 16428
end 16428
start 1860
end 1860
start 12680
end 12680
start 4152
end 4152
start 6004
end 6004
start 15232
end 15232
start 12396
end 12396
start 8104
end 8104
start 15164
end 15164
start 16988
endstart 16596 16988

end 16596
start 3740
end 3740
start 15764
end 15764
start 14460
end 14460
start 4064
end 4064
start 1460

end start 18208
end11192 18208

start 8284
endstart 17676
end 17676
start 4728
end 4728
 8284
start 6868
start 3960
end 3960
end 6868
start 12184
end 12184
start 6460
end 6460
start 16304
end 16304
start 17900
end start 1713617900

end 17136
start 11308
end 11308
start 5516
end 5516
start 18040
end 18040
start 18396
end 18396
start 17476
end 17476
start 12720
end 12720
start 11316
end 11316
start 17436
end 17436
start 12912
end 12912
start 9316
end 9316
start 15984
start 9840end 15984
start 708end 9840


end 708
start 13960
end 13960
start 4132
end 4132
start 17648
end 17648
start 13028
end 13028
start 3644
end 3644
start 10664
end 10664
start 14632
end 14632
start 7480
end 7480
start 9664
end 9664
start 1516
end 1516
start 3236
end 3236
start 2784
end 2784
start 15880
end 15880
start 916
start 8988
end 8988
start 9012
end 9012
end 916
start 620
end 620
start start7760
end  7760
start 16108
end 1610814644

end 14644
start 1224
end 1224
start 2592
end 2592
start 3916
end 3916
start 1677

start 15972
start 3540end
endend 3540 15972
 16408

start 13072
end 13072
start 6312
end 6312
start 3004
end 3004
start start 5840
end 5840
start 91209656
end 9656
start 3976
end 3976

end 9120
start 7268
endstart 628
end 628 7268

start 2640
end 2640
start 16824
end 16824
start 1740
end 1740
start 14480
end 14480
start 5016
end 5016
start 13020
end 13020
start 17068
end 17068
start 4220
start 16860
end 16860
end start 4220
9196
end 9196
start 12712
end 12712
start 5928
end 5928
start start 14404
5412
endstart 15372end 14404 5412

end
 15372
start 14932
end 14932
start 2616
end start 11936
2616end 11936
start
 17796
start 2092
end 2092
start 9908
end 9908
end 17796
start 9420
end 9420
start 3512
end 3512
start 9416
end 9416
start 15552
end 15552
start 9884
end 9884
start 12528
end 12528
start 15096
end 15096
start 6936
end 6936
start 12480
end 12480
start 4856
end 4856
start 13264
end 13264
start 16032
end 16032
start 7712
start 10016
end 10016
start 6680
end 6680endstart 17816

end 17

start 9848
end 9848
12452
end 12452
start 11080
start 8968
end 11080
endstart 16192
 8968
end 16192
start 11312
end 11312
start 8896
end 8896
start 13556
end 13556
start 17636
end 17636
start 18048
end 18048
start 18012
start 1188end 18012

end 1188
start 10552
end 10552start 1676
end 1676

start 13492
end 13492
start 17056
endstart 18352
end 18352
 17056
start 7572
end 7572
start 3968
end 3968
start 924
end 924
start 15800
endstart 10840
start 12060
 15800end 10840end 12060

start 18376
end 18376

start 18160
start 9820
end 9820
end 18160
start 10544
end 10544
start 15996
end 15996
start 1444
end 1444
start 16256
end 16256
start 13308
end 13308
start 496
end 496
start 10652
end 10652
start 6980
end 6980
start 11592
end 11592
start 3572
end 3572
start 18136
end 18136
start 13868
end 13868
startstart 12760
 8372
end 8372
end 12760
start 15772
end 15772
start 18172
endstart  17824
start 11060
end 11060
18172
start 7008end 17824

end 7008
start 16544
startend 16544
 5472
end 5472
start 13

start 7624
end 7624
start 10576
end 10576
start 11960
end 11960
start 13612
end 13612
start 3544
end 3544
start 16532
end 16532
start 13816
end 13816
start 17700
end 17700
start 9404
end 9404
start 18404
end 18404
start 12704
end 12704
start 17968
end 17968
start 2056
end 2056
start 6056
end 6056
start 12516
end 12516
start 10220
end 10220
start 18256
end 18256
start 17304
end 17304
start 8596
end 8596
start 8928
end 8928
start 16404
end 16404
start 10616
endstart 17284
end 17284
 10616
start 588
end 588
start 17288
end 17288
start 2520
end 2520
start 11560
end 11560
start 15104
end 15104
start 16944
end 16944
start 17320
end 17320
start 10820
end 10820
start 11860
end 11860
start 11016
end 11016
start 15664
end 15664
start 7692
start 10208end 7692

end 10208
start 2340
end 2340
start 18344
end 18344start 17944
end 17944

start 14112
end 14112
start 13656
end 13656
start 16896
end 16896
start 15024
start 9456
end 9456
end 15024
start 12000
end 12000
start 8124
end 8124
start 2936
end 2

start  9544
start 18408
17600
end 17600
end 18408
end 9544
start 9240
start 6080
end 6080
end 9240start 2800

end 2800
start 11088
end 11088
start 6612
end 6612
start 2776
end 2776
start 13652
end 13652start 13864
end start 17276
end 17276

13864
start 8516start 6552

end 6552end 8516

start 4904
end 4904start 10184
end
 start 17556
10184end 17556

start 13404
end 13404start 2500
end 2500

start 1884
end 1884
start 4272
end 4272
start 17168
end 17168
start 3832
end 3832
start 3912
end 3912
start 14812
end 14812
start 12096
end 12096
start 12992
end 12992
start 17496
end 17496
start 15144
end 15144
start 8500
end 8500
start 15256
end 15256
start 15924
end 15924
start 9084
end 9084
start 7916
end 7916
start 15544
end 15544
start 14060
end 14060
start 1560
end 1560
start 16348
start 17692end 16348

end 17692
start 14972
end 14972
start 10512
end 10512
start 18312
end 18312
start 16148
end 16148
start 17360
end 17360
start 7328
end 7328
start 18340
end 18340
start 14788
end 14788
start 149

17760
end 17760
start 9988
end 9988
start 18056
end 18056
start 7896
end 7896
start 1032
end 1032
start 1408
start 12228
end 1408
end 12228
start 1244
end 1244
start 13820
end 13820
start 13876
end 13876
start 14672
end 14672
start 9736
end 9736
start 11196
end 11196
start 4632
end 4632
start 9468
end 9468
start 2732
end 2732
start 14792
end 14792
start 16884
end 16884
start 10492
end 10492
start 13116
end 13116
start 13604
end 13604
start 15176
end 15176
start 17984
end 17984
start 18000
end 18000
start 17932
end 17932
start 18296
end 18296
start 11428
end 11428
start 6124
end 6124
start 908
end 908
start 13672
end 13672
start 12420
end 12420
start 7628
end 7628
start 15856
end 15856
start 13800
end 13800
start 7448
end 7448
start 11012
end 11012
start 18152
end 18152
start 6704
end 6704
start 2948
end 2948
start 15652
start 11908end 15652
end 11908

start 6344
end 6344
start 12312
end 12312
start 9080
end 9080
start 7936
end 7936
start 8040
end 8040
start 14584
end 14584
start 16560


start 15000
end 15000
start 9028
end 9028
start 1812
start 12920end 1812

start end 12920
10884
end 10884
start 14300
end 14300
start 17632
end 17632
start 7292
end 7292
start 11920
end 11920
start 18356
end 18356
start 13900
end 13900
start 7180
end 7180
start 14472
end 14472
start 17228
end 17228
start 2712
end 2712
start 13600
end 13600
start 15916
end 15916
start 15388
end 15388
start 12608
end 12608
start 6120
end 6120
start 16208
end 16208
start 17040
end 17040
start 17960
end 17960
start 15352
end 15352
start 8196
end 8196
start 8140
end 8140
start 10668
end 10668
start 8880
end 8880
start 4920
end 4920
start 3588
end 3588
start 17576
end 17576
start 10252
end 10252
start 7412
end 7412
start 15016
end 15016
start 6072
end 6072
start 15808
end 15808
start 16772
end 16772
start 13872
end 13872
start 13512
end 13512
start 12352
start 15080end
 12352
end 15080
start 17808
end 17808
start 6084
start 4924
end 4924
end 6084
start 16020
end 16020
start 9984
end 9984
start 860
end 860
st