In [1]:
import numpy as np
import copy
import math
import random
import sys
sys.path.append('../code/')

from Tester import Tester

In [2]:
tester = Tester()

In [3]:
loop_tiling_lst =   [ 
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
# parallel_for_dims = ["weight", "output"]
parallel_for_dims = None

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  4
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  4
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]

INPUT MEMORY SIZES:
[28, 6]
Optimal Expansion at each level:
[0, 0]
Actual Expansion at each level:
[0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]

WEIGHT MEMORY SIZES:
[64, 8]
****************************************************************************************************

OUTPUT DATA:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT MEM

In [4]:
loop_tiling_lst =   [ 
                        [{"weight": 2}, {"filter": 2}, {"channel": 2}, {"output": 2}],
                        [{"filter": 4}, {"output": 4}, {"channel": 4}, {"weight": 4}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
# parallel_for_dims = ["filter", "channel", "output"]
parallel_for_dims = None

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]]

INPUT MEMORY SIZES:
[120, 28]
Optimal Expansion at each level:
[0, 0]
Actual Expansion at each level:
[0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15

In [5]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
                        [{"channel": 2}, {"filter": 2},  {"output": 2},  {"weight": 2}],
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]]

INPUT MEMORY SIZES:
[120, 28, 6]
Optimal Expansion at each level:
[0, 0, 0]
Actual Expansion at each level:
[0, 0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  1

In [6]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
                        [{"weight": 2}, {"filter": 2},  {"output": 2},  {"channel": 2}],
                        [{"filter": 2}, {"output": 2},  {"channel": 2},  {"weight": 2}]
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"output"}
costs = [10, 7, 3, 1]
expansion_factor = 0

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  16
Num Inputs per Channel:  31
Total Weight Filters:  16
Num Channels per Filter:  16
Num Weights per Filter:  16
Total Output Channels:  16
Num Outputs per Channel:  16

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48
   49  50  51  52  53  54  55  56  57  58  59  60  61]
 [ 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
   80  81  82  83  84  85  86  87  88  89  90  91  92]
 [ 93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
  111 112 113 114 115 116 117 118 119 120 121 122 123]
 [124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141
  142 143 144 145 146 147 148 149 150 151 152 153 154]
 [155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
  173 174 175 176 177 178 179 180 181 182 183 184 185]
 [186 187 188 189 19

In [7]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"output": 3},  {"weight": 3}],
                        [{"filter": 2},  {"channel": 3},  {"weight": 2}, {"output": 3}]
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "output"}
costs = [10, 7]
expansion_factor = 0.5

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  6
Num Inputs per Channel:  14
Total Weight Filters:  4
Num Channels per Filter:  6
Num Weights per Filter:  6
Total Output Channels:  4
Num Outputs per Channel:  9

INPUT DATA:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79 80 81 82 83]]

INPUT MEMORY SIZES:
[84, 13]
Optimal Expansion at each level:
[0, 3]
Actual Expansion at each level:
[0.0, 1.5]
****************************************************************************************************

WEIGHT DATA:
[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]]

 [[ 24  25  26  27  28  29]
  [ 30  31  32  33  34  35]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]]

 [[ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]
  [ 60  61  62  6

In [ ]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 3}, {"output": 2},  {"weight": 3}],
                        [{"filter": 2},  {"channel": 3},  {"weight": 2}, {"output": 2}],
                        [{"filter": 2},  {"channel": 3},  {"output": 3}, {"weight": 2}]
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "output"}
costs = [10, 7, 3]
expansion_factor = 0.5

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  27
Num Inputs per Channel:  23
Total Weight Filters:  8
Num Channels per Filter:  27
Num Weights per Filter:  12
Total Output Channels:  8
Num Outputs per Channel:  12

INPUT DATA:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22]
 [ 23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
   41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
   64  65  66  67  68]
 [ 69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
   87  88  89  90  91]
 [ 92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
  110 111 112 113 114]
 [115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132
  133 134 135 136 137]
 [138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
  156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
  179 180 181 182 183]
 [184 185 186 187 18

In [9]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}],
                        [{"filter": 2},  {"weight": 4},  {"channel": 3}, {"output": 4}],
                        [{"channel": 3}, {"filter": 4},  {"output": 2},  {"weight": 4}],
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  18
Num Inputs per Channel:  63
Total Weight Filters:  24
Num Channels per Filter:  18
Num Weights per Filter:  48
Total Output Channels:  24
Num Outputs per Channel:  16

INPUT DATA:
[[   0    1    2 ...   60   61   62]
 [  63   64   65 ...  123  124  125]
 [ 126  127  128 ...  186  187  188]
 ...
 [ 945  946  947 ... 1005 1006 1007]
 [1008 1009 1010 ... 1068 1069 1070]
 [1071 1072 1073 ... 1131 1132 1133]]

INPUT MEMORY SIZES:
[1134, 207, 15]
Optimal Expansion at each level:
[0, 0, 0]
Actual Expansion at each level:
[0, 0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[    0     1     2 ...    45    46    47]
  [   48    49    50 ...    93    94    95]
  [   96    97    98 ...   141   142   143]
  ...
  [ 1008  1009  1010 ...  1053  1054  1055]
  [ 1056  1057  1058 ...  1101  1102  1103]
  [ 1104  1105  1106 ...  1149  1150  1151]]

 [[ 1152  1153  1154 ...  1197  1198  1199]
  [ 1200  120

In [10]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}],
                        [{"filter": 2},  {"weight": 4},  {"channel": 3}, {"output": 4}],
                        [{"channel": 3}, {"filter": 4},  {"output": 2},  {"weight": 4}],
                    ]

# parallel_for_dims = ["channel", "output"]
parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"weight", "output"}
costs = [10, 7, 3]
expansion_factor = 1

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  18
Num Inputs per Channel:  63
Total Weight Filters:  24
Num Channels per Filter:  18
Num Weights per Filter:  48
Total Output Channels:  24
Num Outputs per Channel:  16

INPUT DATA:
[[   0    1    2 ...   60   61   62]
 [  63   64   65 ...  123  124  125]
 [ 126  127  128 ...  186  187  188]
 ...
 [ 945  946  947 ... 1005 1006 1007]
 [1008 1009 1010 ... 1068 1069 1070]
 [1071 1072 1073 ... 1131 1132 1133]]

INPUT MEMORY SIZES:
[1134, 207, 15]
Optimal Expansion at each level:
[0, 0, 0]
Actual Expansion at each level:
[0, 0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[    0     1     2 ...    45    46    47]
  [   48    49    50 ...    93    94    95]
  [   96    97    98 ...   141   142   143]
  ...
  [ 1008  1009  1010 ...  1053  1054  1055]
  [ 1056  1057  1058 ...  1101  1102  1103]
  [ 1104  1105  1106 ...  1149  1150  1151]]

 [[ 1152  1153  1154 ...  1197  1198  1199]
  [ 1200  120