In [1]:
import numpy as np
import copy
import math
import random
import sys
sys.path.append('../code/')

from Tester import Tester
from software.Memory import Memory

In [2]:
tester = Tester()

In [3]:
loop_tiling_lst =   [ 
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}],
                        [{"channel": 2}, {"filter": 2}, {"weight": 2}, {"output": 2}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
parallel_for_dims = ["weight", "output"]
# parallel_for_dims = None

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=True)
tester.test(full=False)

Total Input Channels:  4
Num Inputs per Channel:  7
Total Weight Filters:  4
Num Channels per Filter:  4
Num Weights per Filter:  4
Total Output Channels:  4
Num Outputs per Channel:  4

INPUT DATA:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]

INPUT MEMORY SIZES:
[28, 6]
Optimal Expansion at each level:
[0, 0]
Actual Expansion at each level:
[0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]

WEIGHT MEMORY SIZES:
[64, 8]
****************************************************************************************************

OUTPUT DATA:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT MEM

In [4]:
loop_tiling_lst =   [ 
                        [{"weight": 2}, {"filter": 2}, {"channel": 2}, {"output": 2}],
                        [{"filter": 4}, {"output": 4}, {"channel": 4}, {"weight": 4}]
                    ]

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 5]
expansion_factor = 0
parallel_for_dims = ["filter", "channel", "output"]

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[2 8 7 7 8 2 7 2 9 0 3 6 9 5 8]
 [3 7 3 7 6 9 7 9 2 9 9 1 2 8 4]
 [6 7 8 7 9 5 4 7 2 1 5 5 3 6 9]
 [8 6 2 4 9 0 5 2 0 7 5 5 6 9 1]
 [5 4 3 0 7 6 6 5 1 5 5 3 5 4 2]
 [3 6 5 8 0 3 0 6 9 6 3 9 3 2 9]
 [4 2 8 8 0 0 6 3 9 2 9 5 3 0 4]
 [9 1 4 7 0 7 6 8 5 0 7 2 5 5 8]]

INPUT MEMORY SIZES:
[120, 28]
Optimal Expansion at each level:
[0, 0]
Actual Expansion at each level:
[0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[9 0 3 8 1 6 0 6]
  [2 6 0 1 1 3 3 2]
  [0 1 2 5 7 0 0 2]
  [5 0 3 1 7 9 7 6]
  [2 7 1 9 3 3 9 8]
  [7 5 1 9 8 1 9 5]
  [8 1 6 6 8 5 2 2]
  [5 6 5 3 1 3 0 0]]

 [[6 0 0 7 2 6 0 0]
  [1 9 7 8 2 7 0 2]
  [0 3 3 3 0 7 9 2]
  [9 6 6 6 7 7 4 2]
  [0 2 8 2 2 8 3 1]
  [6 9 4 2 0 9 8 9]
  [1 5 1 0 1 9 1 5]
  [9 0 9

In [5]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"output": 2},  {"weight": 2}, {"channel": 2}],
                        [{"channel": 2}, {"filter": 2},  {"output": 2},  {"weight": 2}],
                    ]

parallel_for_dims = ["weight", "channel"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=False)
tester.test(full=False)

Total Input Channels:  8
Num Inputs per Channel:  15
Total Weight Filters:  8
Num Channels per Filter:  8
Num Weights per Filter:  8
Total Output Channels:  8
Num Outputs per Channel:  8

INPUT DATA:
[[6 8 3 1 0 5 9 4 1 6 1 2 2 9 0]
 [3 1 1 1 0 2 6 5 7 3 2 7 4 3 1]
 [4 8 6 9 8 8 5 6 8 8 3 3 6 8 3]
 [6 6 7 1 4 7 7 6 7 0 5 6 2 7 0]
 [1 5 5 9 8 7 7 3 6 7 5 7 1 7 6]
 [7 0 9 7 8 0 5 3 5 8 7 4 5 8 8]
 [1 8 6 2 6 8 2 2 9 8 5 7 3 7 8]
 [7 1 9 3 8 0 9 2 3 7 2 2 0 3 2]]

INPUT MEMORY SIZES:
[120, 28, 6]
Optimal Expansion at each level:
[0, 0, 0]
Actual Expansion at each level:
[0, 0, 0]
****************************************************************************************************

WEIGHT DATA:
[[[3 8 4 2 3 6 8 2]
  [9 9 0 4 7 0 2 0]
  [0 3 5 1 8 8 6 8]
  [8 1 2 2 1 3 7 5]
  [0 6 4 6 0 3 2 2]
  [8 9 3 1 8 3 9 4]
  [6 0 4 0 9 5 7 8]
  [9 9 4 5 9 0 7 5]]

 [[4 2 3 7 4 3 9 5]
  [0 1 9 7 4 1 5 8]
  [7 7 2 2 5 1 1 6]
  [5 9 3 9 4 1 8 7]
  [5 3 8 5 3 4 6 7]
  [3 9 2 6 6 3 4 7]
  [4 1 6 4 4 2 8 6]

In [6]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"weight": 2},  {"output": 2}, {"channel": 2}],
                        [{"weight": 2}, {"filter": 2},  {"output": 2},  {"channel": 2}],
                        [{"filter": 2}, {"output": 2},  {"channel": 2},  {"weight": 2}]
                    ]

parallel_for_dims = ["channel", "output"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"output"}
costs = [10, 7, 3, 1]
expansion_factor = 0

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=False)
tester.test(full=False)

Total Input Channels:  16
Num Inputs per Channel:  31
Total Weight Filters:  16
Num Channels per Filter:  16
Num Weights per Filter:  16
Total Output Channels:  16
Num Outputs per Channel:  16

INPUT DATA:
[[1 5 7 6 5 5 8 8 4 8 2 6 1 0 7 7 6 7 6 1 3 2 1 5 6 0 9 6 1 6 0]
 [2 6 2 7 0 6 4 8 1 8 8 2 3 3 2 0 5 4 7 3 8 6 6 9 3 6 5 1 6 0 5]
 [6 4 0 0 7 5 0 2 6 4 0 8 8 7 3 1 1 5 4 7 3 4 0 6 8 4 8 9 3 3 7]
 [0 5 6 8 6 1 1 6 6 9 5 1 9 3 8 6 9 8 4 4 7 4 6 5 9 6 5 2 6 4 1]
 [6 1 5 7 0 0 0 9 5 7 1 1 2 2 7 3 7 3 3 4 0 7 4 6 0 9 7 3 7 0 3]
 [8 3 9 9 4 2 1 6 5 0 1 9 6 5 7 6 4 5 7 1 9 3 8 3 7 9 1 8 0 7 7]
 [8 0 8 2 6 0 8 5 1 0 5 7 5 5 0 3 3 7 8 0 9 4 9 1 3 2 8 3 4 7 7]
 [9 4 3 5 1 7 2 1 5 5 4 7 1 3 4 1 6 1 9 0 5 2 5 9 4 6 3 7 1 9 5]
 [6 7 6 6 9 4 3 3 3 8 0 6 8 5 1 6 9 0 0 6 2 2 4 6 9 8 0 5 2 5 8]
 [8 4 5 7 4 4 4 1 9 9 4 0 9 1 8 8 5 9 6 6 3 7 6 9 2 7 9 9 0 5 3]
 [8 1 3 4 8 9 8 3 4 5 9 0 6 7 9 4 3 3 9 4 2 6 1 9 3 5 0 5 8 5 8]
 [7 1 9 7 8 1 9 4 3 6 9 7 4 3 7 9 6 2 5 7 6 1 6 4 6 1 0 3 5 1 4]
 [3 9 2 9 7 9 

In [7]:
loop_tiling_lst =   [
                        [{"filter": 2},  {"channel": 2}, {"weight": 2},  {"output": 2}],
                        [{"filter": 2},  {"channel": 2},  {"output": 2}, {"weight": 3}],
                        [{"channel": 2}, {"filter": 2},  {"output": 3},  {"weight": 2}],
                        [{"filter": 2}, {"output": 2},  {"channel": 2},  {"weight": 2}]
                    ]

parallel_for_dims = ["weight", "output"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "output"}
costs = [10, 7, 3, 1]
expansion_factor = 0

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=False)
tester.test(full=False)

Total Input Channels:  16
Num Inputs per Channel:  47
Total Weight Filters:  16
Num Channels per Filter:  16
Num Weights per Filter:  24
Total Output Channels:  16
Num Outputs per Channel:  24

INPUT DATA:
[[1 5 1 9 3 3 4 7 9 9 1 6 1 6 4 8 2 4 8 3 5 1 7 6 1 2 7 5 8 7 7 8 0 6 2 5
  8 1 2 1 4 3 8 0 3 9 0]
 [1 9 7 0 6 1 6 1 8 5 5 7 3 2 7 6 4 8 7 8 4 4 6 0 3 6 7 6 3 0 4 9 3 3 6 7
  9 9 3 3 3 3 2 6 7 9 7]
 [9 8 0 2 3 2 4 0 1 6 2 2 0 8 4 2 8 3 8 7 7 5 1 8 4 4 7 5 7 9 1 4 6 4 2 1
  6 8 7 1 0 1 1 9 0 4 9]
 [6 2 0 5 9 9 2 6 6 5 5 5 6 1 5 2 3 1 2 3 4 8 7 1 4 2 5 1 5 5 9 0 2 7 1 8
  8 4 6 4 7 6 0 6 3 4 7]
 [9 5 5 4 3 7 4 5 4 6 6 7 1 3 4 2 6 5 6 9 4 9 1 4 8 9 0 3 8 2 6 8 7 1 6 8
  1 6 7 4 6 8 5 5 4 8 3]
 [7 8 3 3 4 3 1 6 2 1 0 1 0 4 6 9 3 9 4 7 5 2 8 0 7 1 7 1 9 8 8 8 4 3 4 9
  7 9 8 6 5 7 7 4 5 3 1]
 [1 5 6 5 5 6 4 9 6 8 7 8 4 0 6 2 1 7 7 3 4 3 1 2 9 8 3 8 6 9 5 2 5 2 1 2
  9 6 9 9 8 4 8 6 6 8 0]
 [0 2 4 4 0 3 1 4 2 5 2 8 3 9 1 1 6 5 6 1 2 8 4 9 2 7 1 0 9 7 2 1 2 3 1 0
  6 0 7 9 7 5 5 2 3 6 1]
 [

In [8]:
loop_tiling_lst =   [
                        [{"filter": 3},  {"channel": 2}, {"weight": 3},  {"output": 2}],
                        [{"channel": 2},  {"weight": 4},  {"filter": 3}, {"output": 4}],
                        [{"channel": 3}, {"filter": 4},  {"output": 2},  {"weight": 4}],
                    ]

parallel_for_dims = ["filter", "output"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "weight", "output"}
costs = [10, 7, 3]
expansion_factor = 0

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=False)
tester.test(full=False)

Total Input Channels:  12
Num Inputs per Channel:  63
Total Weight Filters:  36
Num Channels per Filter:  12
Num Weights per Filter:  48
Total Output Channels:  36
Num Outputs per Channel:  16

INPUT DATA:
[[0 7 2 2 5 6 9 5 3 3 8 4 3 3 9 9 6 8 6 3 6 3 7 1 5 7 8 5 7 4 2 7 5 7 1 6
  4 6 6 0 3 2 5 1 7 9 9 6 1 2 4 5 2 6 2 0 5 1 4 1 5 5 3]
 [0 9 0 1 9 8 5 7 5 0 9 3 2 0 8 3 0 1 1 2 7 0 9 9 8 6 9 2 7 1 5 7 3 3 4 3
  6 1 1 6 6 2 9 7 0 0 7 0 3 5 6 9 7 0 3 0 3 1 9 0 1 1 3]
 [2 9 2 9 7 4 3 6 3 7 4 0 7 2 2 2 5 7 7 8 9 1 3 2 5 8 0 1 3 3 7 4 2 0 0 1
  8 4 1 8 7 5 4 8 2 8 8 6 8 7 4 3 8 8 7 7 1 2 2 5 6 8 8]
 [0 4 9 4 6 3 6 3 9 5 9 1 7 2 1 5 3 5 2 5 9 5 6 9 5 3 9 1 0 1 0 9 9 4 3 6
  4 2 4 9 4 2 9 3 3 4 6 2 8 1 2 4 5 4 6 2 9 2 6 7 3 8 5]
 [9 0 8 0 8 4 4 1 6 2 0 6 6 9 3 1 9 2 6 0 9 1 4 5 8 7 1 5 0 1 2 6 6 9 3 2
  8 7 0 8 3 5 0 7 1 5 7 7 2 5 8 0 3 6 9 6 5 0 5 7 2 8 5]
 [5 7 1 1 3 9 3 6 4 4 3 0 6 4 1 7 3 0 0 3 7 5 9 1 3 9 0 2 7 2 5 3 1 8 1 9
  0 4 1 5 0 5 4 0 0 1 5 3 3 8 7 5 9 2 8 7 9 3 2 6 2 5 7]
 [6 4 7 

In [9]:
loop_tiling_lst =   [
                        [{"channel": 2}, {"weight": 3}, {"output": 2}, {"filter": 3}],
                        [{"filter": 2},  {"channel": 3},  {"weight": 2}, {"output": 3}]
                    ]

parallel_for_dims = ["filter"]
# parallel_for_dims = None

# which data should write backs be enabled for
write_backs = {"input", "output"}
costs = [10, 7]
expansion_factor = 1

tester.setup(loop_tiling_lst, costs, write_backs, expansion_factor=expansion_factor, parallel_for_dims=parallel_for_dims, debug=False)
tester.test(full=False)

Total Input Channels:  6
Num Inputs per Channel:  11
Total Weight Filters:  6
Num Channels per Filter:  6
Num Weights per Filter:  6
Total Output Channels:  6
Num Outputs per Channel:  6

INPUT DATA:
[[0 0 5 3 9 9 4 3 9 6 0]
 [0 5 7 8 6 7 3 3 4 0 5]
 [0 8 8 1 9 4 3 6 5 1 7]
 [4 9 1 9 2 9 1 6 8 8 1]
 [5 9 0 5 2 9 9 0 6 7 3]
 [5 9 2 6 2 3 9 1 5 5 7]]

INPUT MEMORY SIZES:
[66, 15]
Optimal Expansion at each level:
[0, 3]
Actual Expansion at each level:
[0, 3]
****************************************************************************************************

WEIGHT DATA:
[[[9 6 9 1 2 0]
  [0 6 2 0 7 2]
  [8 4 7 2 4 0]
  [9 5 6 9 7 6]
  [4 2 0 1 0 2]
  [7 2 9 5 6 1]]

 [[2 4 5 2 8 6]
  [1 2 6 9 5 3]
  [1 1 1 4 6 3]
  [5 5 2 5 0 6]
  [0 2 3 5 0 2]
  [1 5 1 5 2 2]]

 [[6 5 3 1 2 6]
  [4 1 9 3 0 0]
  [4 2 1 5 9 1]
  [8 2 9 0 4 7]
  [0 8 8 7 7 2]
  [4 5 5 0 3 4]]

 [[3 9 9 6 4 5]
  [3 9 8 9 4 3]
  [5 5 4 1 4 6]
  [7 5 0 2 1 1]
  [8 4 7 6 3 3]
  [3 5 5 6 8 4]]

 [[6 7 5 1 6 1]
  [8 3 4 0 7 1]
 